name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
            # Now we have got the access of EC2 and we will start the deploy
            cd /home/ubuntu/GajahSafe
            git pull origin main
            npm install
            sudo npm install -g pm2

            # Check if the application is already running
            if pm2 describe app_name > /dev/null; then
              pm2 restart app_name
            else
              pm2 start /home/ubuntu/GajahSafe/your_startup_file.js --name "app_name"
            fi
          EOF
